### ISSUE TITLE
Can i use lib in Node JS?

### ISSUE THREAD

**Issue by intosKai** [tezbridge/tezbridge-crypto#2]
When I trying use TezBridgeCrypto.crypto.getKeyFromSecretKey(sk) i get an error.
```
import TezBridgeCrypto from './tezbridge-crypto/Pt24m4xi';
       ^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```
If I using require:
```
import codec from '../PsddFKi3/codec'
       ^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/petr/WebstormProjects/test1/src/index.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

```

**Comment by catsigma** [comment]
Sorry, but you cannot directly `require` the package. There is no pre-built js file in this package.

So you need to use `parcel-bundler` or `webpack` to build your code.
